// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/exec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputChannel int32

const (
	OutputChannel_STDOUT OutputChannel = 0
	OutputChannel_STDERR OutputChannel = 1
)

// Enum value maps for OutputChannel.
var (
	OutputChannel_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	OutputChannel_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x OutputChannel) Enum() *OutputChannel {
	p := new(OutputChannel)
	*p = x
	return p
}

func (x OutputChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_exec_proto_enumTypes[0].Descriptor()
}

func (OutputChannel) Type() protoreflect.EnumType {
	return &file_proto_exec_proto_enumTypes[0]
}

func (x OutputChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputChannel.Descriptor instead.
func (OutputChannel) EnumDescriptor() ([]byte, []int) {
	return file_proto_exec_proto_rawDescGZIP(), []int{0}
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_proto_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_exec_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *OpenSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Channel       OutputChannel          `protobuf:"varint,2,opt,name=channel,proto3,enum=grpc.OutputChannel" json:"channel,omitempty"`
	End           bool                   `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_proto_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_proto_exec_proto_rawDescGZIP(), []int{2}
}

func (x *CommandOutput) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *CommandOutput) GetChannel() OutputChannel {
	if x != nil {
		return x.Channel
	}
	return OutputChannel_STDOUT
}

func (x *CommandOutput) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_exec_proto protoreflect.FileDescriptor

const file_proto_exec_proto_rawDesc = "" +
	"\n" +
	"\x10proto/exec.proto\x12\x04grpc\"I\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xbf\x01\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12/\n" +
	"\x03env\x18\x03 \x03(\v2\x1d.grpc.ExecuteRequest.EnvEntryR\x03env\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\rCommandOutput\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12-\n" +
	"\achannel\x18\x02 \x01(\x0e2\x13.grpc.OutputChannelR\achannel\x12\x10\n" +
	"\x03end\x18\x03 \x01(\bR\x03end\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode*'\n" +
	"\rOutputChannel\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x012\x85\x01\n" +
	"\vExecService\x12>\n" +
	"\vOpenSession\x12\x18.grpc.OpenSessionRequest\x1a\x13.grpc.CommandOutput0\x01\x126\n" +
	"\aExecute\x12\x14.grpc.ExecuteRequest\x1a\x13.grpc.CommandOutput0\x01B6Z4github.com/codepod/codepod/sandbox/agent/pkg/grpc/pbb\x06proto3"

var (
	file_proto_exec_proto_rawDescOnce sync.Once
	file_proto_exec_proto_rawDescData []byte
)

func file_proto_exec_proto_rawDescGZIP() []byte {
	file_proto_exec_proto_rawDescOnce.Do(func() {
		file_proto_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exec_proto_rawDesc), len(file_proto_exec_proto_rawDesc)))
	})
	return file_proto_exec_proto_rawDescData
}

var file_proto_exec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_exec_proto_goTypes = []any{
	(OutputChannel)(0),         // 0: grpc.OutputChannel
	(*OpenSessionRequest)(nil), // 1: grpc.OpenSessionRequest
	(*ExecuteRequest)(nil),     // 2: grpc.ExecuteRequest
	(*CommandOutput)(nil),      // 3: grpc.CommandOutput
	nil,                        // 4: grpc.ExecuteRequest.EnvEntry
}
var file_proto_exec_proto_depIdxs = []int32{
	4, // 0: grpc.ExecuteRequest.env:type_name -> grpc.ExecuteRequest.EnvEntry
	0, // 1: grpc.CommandOutput.channel:type_name -> grpc.OutputChannel
	1, // 2: grpc.ExecService.OpenSession:input_type -> grpc.OpenSessionRequest
	2, // 3: grpc.ExecService.Execute:input_type -> grpc.ExecuteRequest
	3, // 4: grpc.ExecService.OpenSession:output_type -> grpc.CommandOutput
	3, // 5: grpc.ExecService.Execute:output_type -> grpc.CommandOutput
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_exec_proto_init() }
func file_proto_exec_proto_init() {
	if File_proto_exec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exec_proto_rawDesc), len(file_proto_exec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exec_proto_goTypes,
		DependencyIndexes: file_proto_exec_proto_depIdxs,
		EnumInfos:         file_proto_exec_proto_enumTypes,
		MessageInfos:      file_proto_exec_proto_msgTypes,
	}.Build()
	File_proto_exec_proto = out.File
	file_proto_exec_proto_goTypes = nil
	file_proto_exec_proto_depIdxs = nil
}
